version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1512
      POSTGRES_DB: MatchmakingDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api1:
    build:
      context: .
      dockerfile: MatchmakingEngine/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=MatchmakingDb;Username=postgres;Password=1512
      - Redis__Configuration=redis:6379
      - Jwt__Key=ThisIsMySuperSecretKeyForJwtTokens123! 
    depends_on:
      - postgres
      - redis

  api2:
    build:
      context: .
      dockerfile: MatchmakingEngine/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=MatchmakingDb;Username=postgres;Password=1512
      - Redis__Configuration=redis:6379
      - Jwt__Key=ThisIsMySuperSecretKeyForJwtTokens123!
      - RunMatchmakingWorker=false 
    depends_on:
      - postgres
      - redis

volumes:
  pgdata: