<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>97d931e6-e5ae-4935-9cbc-898baaf8e829</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="MediatR" Version="14.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.10" />
		<PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
		<Compile Remove="MatchmakingEngine.Tests\**" />
		<Content Remove="MatchmakingEngine.Tests\**" />
		<EmbeddedResource Remove="MatchmakingEngine.Tests\**" />
		<None Remove="MatchmakingEngine.Tests\**" />
		<InternalsVisibleTo Include="MatchmakingEngine.Tests" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\MatchmakingEngine.Application\MatchmakingEngine.Application.csproj" />
	  <ProjectReference Include="..\MatchmakingEngine.Infrastructure\MatchmakingEngine.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Domain\" />
	</ItemGroup>

</Project>
